# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubygems-json-list}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel DeLeo"]
  s.date = %q{2010-05-02}
  s.description = %q{      List local and remote gems and return the ouput as JSON
}
  s.email = %q{dan@kallistec.com}
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "LICENSE",
     "Rakefile",
     "VERSION",
     "lib/rubygems/commands/json_list_command.rb",
     "lib/rubygems_plugin.rb"
  ]
  s.homepage = %q{http://github.com/danielsdeleo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6.1}
  s.summary = %q{Gem Command to return the results of gem list as json}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["~> 1.4.1"])
    else
      s.add_dependency(%q<json>, ["~> 1.4.1"])
    end
  else
    s.add_dependency(%q<json>, ["~> 1.4.1"])
  end
end

